name: ecommerce_analytics
version: 1.0.0
config-version: 2

profile: ecommerce_analytics

model-paths:
  - models
macro-paths:
  - macros
test-paths:
  - tests
seed-paths:
  - seeds
snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages
  - logs

models:
  ecommerce_analytics:
    staging:
      +schema: "{{ env_var('STG_DATASET_ID') }}"
      +materialized: table
    intermediate:
      +schema: "{{ env_var('INT_DATASET_ID') }}"
      +materialized: table
    marts:
      +schema: "{{ env_var('MART_DATASET_ID') }}"
      +materialized: table
